# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('../frontend/dist', 'dist'),
    ],
    hiddenimports=[
        'sqlcipher3',
        'pysqlcipher3',
        'pysqlcipher3.dbapi2',
        'nacl',
        'nacl.signing',
        'nacl.public',
        'nacl.secret',
        'nacl.utils',
        'nacl.pwhash',
        'prophet',
        'prophet.forecaster',
        'prophet.plot',
        'cmdstanpy',
        'pandas',
        'numpy',
        'pydantic',
        'pydantic_core',
        'fastapi',
        'uvicorn',
        'sqlalchemy',
        'httpx',
        'pydantic_settings',
        'passlib',
        'bcrypt',
        'python_multipart',
        'email_validator',
        'orjson',
        'loguru',
        'holidays',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'PIL',
        'IPython',
        'jupyter',
        'notebook',
        'pytest',
        'setuptools',
        'wheel',
        'pip',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='LeuitApp',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)